#' Create a Simulation Machine Specification
#' 
#' @param num_claims Number of expected records to generate.
#' @param lob_distribution A length 4 vector. Distribution of claims among the 
#'   four LOBs.
#' @param inflation A length 4 vector. Grow parameters (per LOB) for the numbers
#'    of claims in the 12 accident years.
#' @param sd_claim Value of the standard deviation used in the log-normal 
#'   distribution of the claim sizes.
#' @param sd_recovery  Value of the standard deviation used in the log-normal 
#'   distribution of the recovery sizes.
#' @return An incantation object.
#' @export
simulation_machine <- function(num_claims,
                               lob_distribution,
                               inflation, sd_claim, sd_recovery) {
  conjuror::scribe(
    simulator = "simulation_machine",
    num_claims = num_claims,
    lob_distribution = lob_distribution,
    inflation = inflation,
    sd_claim = sd_claim,
    sd_recovery = sd_recovery
  )
}

#' @importFrom conjuror conjure
#' @export
conjuror::conjure

#' Simulate Claim Histories
#' 
#' @param incantation An `incantation` object returned by `simulation_machine()`.
#' @param ... Optional additional arguments, currently unused.
#' @param seed Seed for random number generation.
#' @param seed_features (Optional) For backwards compatibility; see Details.
#' @param rows_per_partition (Optional) For parallel processing, number of 
#'   observations that are treated at the same time.
#'   
#' @details In the original Simulation Machine paper, a second "seed" parameter
#'   is available to be set that controls the randomness of the feature generation
#'   stage of the simulation. The `seed_features` parameter is included for
#'   users who wish to reproduce the datasets generated by the original accompanying
#'   code. However, for most usage this parameter can be ignored, and is set
#'   equal to the `seed` argument by default.
#'   
#' @export
conjure.simulation_machine <- function(incantation, seed = NULL, 
                                       seed_features = seed,
                                       rows_per_partition = NULL, ...) {
  features <- Feature.Generation(
    V = incantation[["num_claims"]],
    LoB.dist = incantation[["lob_distribution"]],
    inflation = incantation[["inflation"]],
    seed = seed_features
  )
  
  if (is.null(rows_per_partition)) {
    rows_per_partition <- nrow(features)
  }
  
  records <- Simulation.Machine(
    features,
    npb = rows_per_partition,
    seed1 = seed,
    std1 = incantation[["sd_claim"]],
    std2 = incantation[["sd_recovery"]]
  )
  
  tidy_records(records)
}

#' @export
print.simulation_machine <- function(x, ...) {
  num_claims <- x[["num_claims"]]
  lob_distribution <- x[["lob_distribution"]]
  inflation <- x[["inflation"]]
  sd_claim <- x[["sd_claim"]]
  sd_recovery <- x[["sd_recovery"]]
  
  print(glue::glue("
A simulation incantation for `simulation_machine`

Each record is:
 - A snapshot of a claim's incremental paid loss and claim status
   at a development year.

Specs:
 - Expected number of claims: {format(num_claims, big.mark = ',', scientific = FALSE)}
 - LOB distribution: {paste0(lob_distribution, collapse = ', ')}
 - Inflation: {paste0(inflation, collapse = ', ')}
 - SD of claim sizes: {sd_claim},
 - SD of recovery sizes: {sd_recovery}
"))
}
